# yaml-language-server: $schema=https://xtp.dylibso.com/assets/wasm/schema.json
version: v1-draft
exports:
  reflectJsonObject:
    description: |
      This function takes a KitchenSinkObject and returns a KitchenSinkObject.
      It should come out the same way it came in.
    codeSamples:
      - lang: typescript
        source: |
          // pass this through the host function and return it back
          return reflectJsonObjectHost(input)
      - lang: go
        source: |-
          reflect, err := ReflectJsonObjectHost(input)
          if err != nil {
            return input, err
          }

          return *reflect, err
      - lang: csharp
        source: |-
          return Host.ReflectJsonObjectHost(input);
      - lang: zig
        source: |
          return Host.reflectJsonObjectHost(input);
      - lang: rust
        source: |
          pdk::reflect_json_object_host(_input)
      - lang: c++
        source: |
          return pdk::reflectJsonObjectHost(std::move(input));
      - lang: python
        source: |
          return reflect_json_object_host(input)
    input:
      contentType: application/json
      $ref: "#/components/schemas/KitchenSinkObject"
    output:
      contentType: application/json
      $ref: "#/components/schemas/KitchenSinkObject"
  reflectUtf8String:
    description: |
      This function takes a string and returns it.
      Should come out the same way it came in.
    codeSamples:
      - lang: typescript
        source: |
          return reflectUtf8StringHost(input)
      - lang: go
        source: |-
          reflect, err := ReflectUtf8StringHost(input)
          if err != nil {
            return "", err
          }

          return *reflect, nil
      - lang: csharp
        source: |-
          return Host.ReflectUtf8StringHost(input);
      - lang: zig
        source: |
          return Host.reflectUtf8StringHost(input);
      - lang: rust
        source: |
          pdk::reflect_utf8_string_host(_input)
      - lang: c++
        source: |
          return pdk::reflectUtf8StringHost(std::move(input));
      - lang: python
        source: |
          return reflect_utf8_string_host(input)
    input:
      type: string
      description: The input string
      contentType: text/plain; charset=utf-8
    output:
      type: string
      description: The output string
      contentType: text/plain; charset=utf-8
  reflectByteBuffer:
    description: |
      This function takes a byte buffer and returns it.
      Should come out the same way it came in.
    codeSamples:
      - lang: typescript
        source: |
          return reflectByteBufferHost(input)
      - lang: go
        source: |-
          reflect, err := ReflectByteBufferHost(input)
          if err != nil {
            return nil, err
          }

          return reflect, nil
      - lang: csharp
        source: |-
          return Host.ReflectByteBufferHost(input);
      - lang: zig
        source: |
          return Host.reflectByteBufferHost(input);
      - lang: rust
        source: |
          pdk::reflect_byte_buffer_host(_input)
      - lang: c++
        source: |
          return pdk::reflectByteBufferHost(std::move(input));
      - lang: python
        source: |
          return reflect_byte_buffer_host(input)
    input:
      contentType: application/x-binary
      type: buffer
      description: The input byte buffer
    output:
      contentType: application/x-binary
      type: buffer
      description: The output byte buffer

  noInputWithOutput:
    description: a function that takes no input, but returns an output
    output:
      contentType: text/plain; charset=utf-8
      type: string
    codeSamples:
      - lang: typescript
        source: |
          return noInputWithOutputHost();
      - lang: zig
        source: |-
          return Host.noInputWithOutputHost();
      - lang: go
        source: |
          output, err := NoInputWithOutputHost()
          if err != nil {
            return *output, err
          }

          return *output, nil
      - lang: rust
        source: |
          pdk::no_input_with_output_host()
      - lang: csharp
        source: |-
          return Host.NoInputWithOutputHost();
      - lang: c++
        source: |
          return pdk::noInputWithOutputHost();
      - lang: python
        source: |
          return no_input_with_output_host()

  withInputNoOutput:
    description: a function that takes input, but returns no output
    input:
      contentType: application/json
      type: integer
    codeSamples:
      - lang: typescript
        source: |
          return withInputNoOutputHost(input);
      - lang: zig
        source: |-
          return Host.withInputNoOutputHost(input);
      - lang: go
        source: |
          err := WithInputNoOutputHost(input)
          if err != nil {
            return err
          }
          return nil
      - lang: rust
        source: |
          pdk::with_input_no_output_host(_input)
      - lang: csharp
        source: |-
          Host.WithInputNoOutputHost(input);
      - lang: c++
        source: |
          return pdk::withInputNoOutputHost(input);
      - lang: python
        source: |
          return with_input_no_output_host(input)

  noInputNoOutput:
    description: a function that takes no input, and returns no output
    codeSamples:
      - lang: typescript
        source: |-
          noInputNoOutputHost();
      - lang: zig
        source: |-
          return Host.noInputNoOutputHost();
      - lang: go
        source: |
          return NoInputNoOutputHost()
      - lang: rust
        source: |
          pdk::no_input_no_output_host()
      - lang: csharp
        source: |-
          Host.NoInputNoOutputHost();
      - lang: c++
        source: |
          pdk::noInputNoOutputHost();
          return std::expected<void, pdk::Error>();
      - lang: python
        source: |
          return no_input_no_output_host()
  
  helloToGoodbyeReplacement:
    description: a function that should replace `Hello` with `Goodbye` within a byte buffer field on KitchenSinkObject
    input:
      contentType: application/json
      $ref: "#/components/schemas/KitchenSinkObject"
    output:
      contentType: application/json
      $ref: "#/components/schemas/KitchenSinkObject"
    codeSamples:
      - lang: typescript
        source: |-
          const encoder = new TextEncoder()
          const oldBytes = encoder.encode("Hello")
          const newBytes = encoder.encode("Goodbye")
          const bufferView = new Uint8Array(input.aBuffer!)
          const newBuffer = new ArrayBuffer(newBytes.length + bufferView.length - oldBytes.length)
          const newBufferView = new Uint8Array(newBuffer)
          newBufferView.set(newBytes, 0)
          newBufferView.set(bufferView.subarray(oldBytes.length), newBytes.length)
          input.aBuffer = newBuffer
          return input
      - lang: go
        source: |-
          old := []byte("Hello")
          new := []byte("Goodbye")
          input.ABuffer = append(new, input.ABuffer[len(old):]...)

          return input, nil
      - lang: csharp
        source: |-
          var buffer = System.Text.Encoding.UTF8.GetString(input.ABuffer);
          buffer = buffer.Replace("Hello", "Goodbye");
          input.ABuffer = System.Text.Encoding.UTF8.GetBytes(buffer);
          return input;
      - lang: rust
        source: |-
          let mut output = _input;
          output.a_buffer = std::str::from_utf8(&output.a_buffer)?.replace("Hello", "Goodbye").as_bytes().to_vec();
          Ok(output)
      - lang: zig
        source: |-
          var output = input;
          const old = "Hello";
          const new = "Goodbye";
          var arr = std.ArrayList(u8).init(std.heap.wasm_allocator);

          try arr.insertSlice(0, new);
          try arr.insertSlice(new.len, input.aBuffer[old.len..]);
          output.aBuffer = try arr.toOwnedSlice();
          return output;
      - lang: c++
        source: |-
          std::string tomodify = std::string(
              reinterpret_cast<char *>(input.aBuffer.data()), input.aBuffer.size());
          const std::string search("Hello");
          size_t pos = 0;
          if ((pos = tomodify.find(search, pos)) != std::string::npos) {
            tomodify.replace(pos, search.length(), "Goodbye");
            const auto pString = reinterpret_cast<uint8_t *>(tomodify.data());
            input.aBuffer = std::vector<uint8_t>(pString, pString + tomodify.size());
          }
          return std::make_unique<pdk::KitchenSinkObject>(std::move(input));
      - lang: python
        source: |
          input.aBuffer = input.aBuffer.replace(b"Hello", b"Goodbye"); return input

  reflextMixedObject:
    description: a function that takes a mixedobject and returns one testing required vs nullable
    codeSamples:
      - lang: typescript
        source: |
          return input
      - lang: go
        source: |-
          return *input, err
      - lang: csharp
        source: |-
          return input;
      - lang: zig
        source: |
          return input;
      - lang: rust
        source: |
          return _input
      - lang: c++
        source: |
          return std::move(input);
      - lang: python
        source: |
          return input
    input:
      contentType: application/json
      $ref: "#/components/schemas/AMixedRequiredNullableObject"
    output:
      contentType: application/json
      $ref: "#/components/schemas/AMixedRequiredNullableObject"

imports:
  reflectJsonObjectHost:
    description: |
      This function takes a KitchenSinkObject and returns a KitchenSinkObject.
      It should come out the same way it came in. It's the same as the export.
      But the export should call this.
    input:
      contentType: application/json
      $ref: "#/components/schemas/KitchenSinkObject"
    output:
      contentType: application/json
      $ref: "#/components/schemas/KitchenSinkObject"
  reflectUtf8StringHost:
    description: |
      This function takes a string and returns it.
      Should come out the same way it came in. Same as export.
    input:
      type: string
      description: The input string
      contentType: text/plain; charset=utf-8
    output:
      type: string
      description: The output string
      contentType: text/plain; charset=utf-8
  reflectByteBufferHost:
    description: |
      This function takes a bugger and returns it.
      Should come out the same way it came in. Same as export.
    input:
      contentType: application/x-binary
      type: buffer
      description: The input byte buffer
    output:
      contentType: application/x-binary
      type: buffer
      description: The output byte buffer

  noInputWithOutputHost:
    description: a function that takes no input, but returns an output
    output:
      contentType: text/plain; charset=utf-8
      type: string

  withInputNoOutputHost:
    description: a function that takes input, but returns no output
    input:
      contentType: application/json
      type: integer

  noInputNoOutputHost:
    description: a function that takes no input, and returns no output

components:
  schemas:
    AMixedRequiredNullableObject:
      description: An object which demonstrates different combinations of nullable and required
      required:
        - aRequiredNullableBool
        - aRequiredNonNullableBool
      properties:
        aRequiredNonNullableBool:
          type: boolean
        aRequiredNullableBool:
          type: boolean
          nullable: true
        aNonRequiredNonNullableBool:
          type: boolean
        aNonRequiredNullableBool:
          type: boolean
          nullable: true
    EmbeddedObject:
      description: An embedded object, has some arrays too
      required:
        - aBoolArray
        - aStringArray
        - anEnumArray
        - anIntArray
        - aDate
      properties:
        aBoolArray:
          description: an array of bools
          type: array
          items:
            type: boolean
        aStringArray:
          description: an array of strings
          type: array
          items:
            type: string
        anEnumArray:
          description: an array of enums
          type: array
          items:
            $ref: "#/components/schemas/AStringEnum"
        anIntArray:
          description: an array of enums
          type: array
          items:
            type: integer
        aDate:
          description: a date
          type: string
          format: date-time
    AStringEnum:
      description: A string enum
      type: string
      enum:
        - option1
        - option2
        - option3
    KitchenSinkObject:
      description: A json object with every type of property
      required:
        - aString
        - anInt
        - aDouble
        - aFloat
        - aBool
        - anUntypedObject
        - anEnum
        - anEmbeddedObject
        - anEmbeddedObjectArray
        - aDate
        - aBuffer
      properties:
        anOptionalString:
          type: string
          description: A string but not required
          nullable: true
        aString:
          type: string
          description: A String
        anInt:
          type: integer
          description: An Integer
        aFloat:
          type: number
          format: float
          description: A Float
        aDouble:
          type: number
          format: double
          description: A Double
        aBool:
          type: boolean
          description: A Boolean
        anUntypedObject:
          type: object
          description: An untyped object
        anEnum:
          description: A string enum (prop comment)
          $ref: "#/components/schemas/AStringEnum"
        anEmbeddedObject:
          description: A embedded object array(prop comment)
          $ref: "#/components/schemas/EmbeddedObject"
        anEmbeddedObjectArray:
          description: A embedded object array (prop comment)
          type: array
          items:
            $ref: "#/components/schemas/EmbeddedObject"
        aDate:
          description: a date
          type: string
          format: date-time
        aBuffer:
          description: a byte buffer
          type: buffer
