version: v1-draft
exports:
  - name: reflectObject
    description: |
      This function takes a KitchenSinkObject and returns a KitchenSinkObject.
      It should come out the same way it came in.
    codeSamples:
      - lang: typescript
        source: |
          // pass this through the host function and return it back
          return reflectObjectHost(input)
    input:
      $ref: "#/schemas/KitchenSinkObject"
    output:
      $ref: "#/schemas/KitchenSinkObject"
imports:
  - name: reflectObjectHost
    description: |
      This function takes a KitchenSinkObject and returns a KitchenSinkObject.
      It should come out the same way it came in. It's the same as the export.
      But the export should call this.
    input:
      $ref: "#/schemas/KitchenSinkObject"
    output:
      $ref: "#/schemas/KitchenSinkObject"
schemas:
  - name: EmbeddedObject
    description: An embedded object, has some arrays too
    required:
      - aBoolArray
      - anEnumArray
      - aStringArray
      - anIntArray
    properties:
      - name: aBoolArray
        description: an array of bools
        type: array
        items:
          type: boolean
      - name: aStringArray
        description: an array of strings
        type: array
        items:
          type: string
      - name: anEnumArray
        description: an array of enums
        type: array
        items:
          $ref: "#/schemas/AStringEnum"
      - name: anIntArray
        description: an array of enums
        type: array
        items:
          type: integer
  - name: AStringEnum
    description: A string enum
    type: string
    enum:
      - option1
      - option2
      - option3
  - name: KitchenSinkObject
    contentType: application/json
    description: A json object with every type of property
    required:
      - aString
      - anInt
      - aFloat
      - aDouble
      - aBool
      - anEnum
      - anEmbeddedObject
      - anEmbeddedObjectArray
      #- anUntypedObject
    properties:
      - name: anOptionalString
        type: string
        description: A string but not required
      - name: aString
        type: string
        description: A String
      - name: anInt
        type: integer
        description: An Integer
      - name: aFloat
        type: number
        format: float
        description: A Float
      - name: aDouble
        type: number
        format: double
        description: A Double
      - name: aBool
        type: boolean
        description: A Boolean
      # TODO put back after bug fix
      # - name: anUntypedObject
      #   type: object
      #   description: An untyped object
      - name: anEnum
        description: A string enum (prop comment)
        $ref: "#/schemas/AStringEnum"
      - name: anEmbeddedObject
        description: A embedded object array(prop comment)
        $ref: "#/schemas/EmbeddedObject"
      - name: anEmbeddedObjectArray
        description: A embedded object array (prop comment)
        type: array
        items:
          $ref: "#/schemas/EmbeddedObject"
